Homebrew
Install without confirmation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -35,10 +35,10 @@ script:
   - make install_commandlinetools
   - xcode-select -p
 
-  - hash brew 2>/dev/null || { \
-      echo >&2 "I require foo but it's not installed."; }
   - make install_homebrew
   - export PATH=/usr/local/bin:$PATH
+  - hash brew 2>/dev/null || { \
+      echo >&2 "brew not installed. Aborting."; exit 1; }
   - brew --version
 
   - make clean
